Fix insecure remote script execution in workflow

diff --git a/.github/workflows/WRT-CORE.yml b/.github/workflows/WRT-CORE.yml
--- a/.github/workflows/WRT-CORE.yml
+++ b/.github/workflows/WRT-CORE.yml
@@ -75,7 +75,14 @@ jobs:
           sudo -E apt -yqq autoclean
           sudo -E apt -yqq clean
           sudo -E apt -yqq install dos2unix libfuse-dev python3-setools python3-setuptools
-          sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.org/init_build_environment.sh)'
+          curl -sL -o init_build_environment.sh https://build-scripts.immortalwrt.org/init_build_environment.sh
+          if echo "85f4b2c2aa16f8178b57250f5d2bcf4a2e0707c6b569a3b07510f41fc6185dd8  init_build_environment.sh" | sha256sum -c -; then
+            sudo bash init_build_environment.sh
+          else
+            echo "Checksum verification failed!" >&2
+            exit 1
+          fi
+          rm -f init_build_environment.sh
           sudo -E systemctl daemon-reload
           sudo -E timedatectl set-timezone "Asia/Shanghai"
 
